### PR TITLE
Fix dependencies; add test build to ci

### PR DESCRIPTION
**Pull request by why-not-try-calmer**

### CODE REVIEW

**Comment by why-not-try-calmer** [comment]
> Thanks for the speedy reaction! It would be great to have the smoke test in place!
> 
> I would either rename the workflow or even better add a separate file.
> 
> BTW, this is one of the reasons I prefer having all deps in the `requirements.txt`.

`lint-test.yaml` would be ok?

**Comment by suricactus** [comment]
> > Thanks for the speedy reaction! It would be great to have the smoke test in place!
> > I would either rename the workflow or even better add a separate file.
> > BTW, this is one of the reasons I prefer having all deps in the `requirements.txt`.
> 
> `pre-commit.yml` -> `lint-test.yml` would be ok? With different files you need to write more logic to avoid proceeding with a workflow that should not occur when the test / build fails.

Yes, it is ok. Or `lint-and-test`, `lint-and-build`, even `continuous-integration` to keep it generic.

Also change the name of the workflow in line 1: `name: pre-commit`.

**Comment by why-not-try-calmer** [comment]
Not sure what this about though
image

**Comment by why-not-try-calmer** [comment]
Ah, branch protection rules I guess. I don't have the rights to update that.

**Review by suricactus — APPROVED** [review]

**Comment by suricactus** [comment]
Still fails, interesting. It works fine locally.

**Comment by why-not-try-calmer** [comment]
... and remotely: https://github.com/opengisch/QField-docs/actions/runs/6628670609/job/18006277873

**Comment by why-not-try-calmer** [comment]
Ah I bet you 10 lev that it's material-insiders replacing the correct dependencies with incorrect ones.

**Comment by suricactus** [comment]
Ok, locally I managed to reproduce, at least for me it uses the wrong `mkdocs` command. We should revert installing the extensions module too, see the first paragraph https://pypi.org/project/mkdocs-material-extensions/ .

Will debug later tonight.

**Comment by why-not-try-calmer** [comment]
> Ok, locally I managed to reproduce, at least for me it uses the wrong `mkdocs` command. We should revert installing the extensions module too, see the first paragraph https://pypi.org/project/mkdocs-material-extensions/ .
> 
> Will debug later tonight.

Okay but if it uses the wrong mkdocs command, I wonder why https://github.com/opengisch/QField-docs/actions/runs/6628670609/job/18006277873 did not fail?

**Pull request merged**
