### PR TITLE
doc about adding QFC storage

### PR DESCRIPTION
**Pull request by lucienicolier**

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-2642 Document add storage on QFC](https://app.clickup.com/t/2192114/QF-2642)

**Comment by suricactus** [comment]
I think they should be different screenshots, it took me a bit of time to understand why we have the next to each other.

Also, showing the final screen where one can select the actual storage is also useful.

**Comment by m-kuhn** [comment]
@lucienicolier can you check @suricactus comment?

**Comment by m-kuhn** [comment]
@lucienicolier should the images in here appear different from images on other pages?

**Comment by lucienicolier** [comment]
> @lucienicolier should the images in here appear different from images on other pages?

The first image is on the right, compared to others one

**Comment by m-kuhn** [comment]
@lucienicolier 
That's a problem of the image, not markdown: https://github.com/opengisch/QField-docs/pull/324/files?w=1

**Comment by lucienicolier** [comment]
@m-kuhn I don't know what happened.

Could you please verify if everything is fine? Thanks

**Pull request merged**
