### PR TITLE
Update system.en.md

### PR DESCRIPTION
**Pull request by itsakifa**
trying to adapt the action names to those used in the QFieldSync GUI and adding some more detailed explanations on the different working modes.

### CODE REVIEW

**Comment by nirvn** [comment]
@suricactus , if you have some time to review this, would be helpful.

**Comment by suricactus** [comment]
@itsakifa @nirvn the review of this one is a long one, I already started locally with some improvements over this PR which I hope I can push by the end of the week.

**Comment by itsakifa** [comment]
@suricactus do you need anything more from my side?

**Comment by suricactus** [comment]
Closing this in favor of https://github.com/opengisch/QField-docs/pull/508

**Pull request closed without merging**
