### PR TITLE
fix commit

### PR DESCRIPTION
**Pull request by lucienicolier**
Add missing languages

### CODE REVIEW

**Review by mbernasocchi — APPROVED** [review]

**Review by m-kuhn — APPROVED** [review]

**Comment by m-kuhn** [comment]
@lucienicolier you can merge this, it has been approved

**Comment by suricactus** [comment]
@lucienicolier , wait, we are not pushing the docs.

**Comment by m-kuhn** [comment]
:zipper_mouth_face:

**Comment by suricactus** [comment]
It was fake news, I was looking at the wrong action. Anyway, I had to fix the commit message.

@lucienicolier the stage is yours

**Review by suricactus — APPROVED** [review]

**Pull request merged**
