### PR TITLE
Warning! Data lost from External SD card when uninstall qfield!

### PR DESCRIPTION
**Pull request by giedrioks26**
[#143](https://github.com/opengisch/QField/issues/143)

### CODE REVIEW

**Comment by m-kuhn** [comment]
Interesting, that's a bit of a bummer.

Does it also work if you put the data into a different folder on the external SD card?

**Comment by giedrioks26** [comment]
No. Only on /Android/data/ch.opengis.qfield/. But then do not allow editing data. Only internal card can be placed in different folders.

**Comment by m-kuhn** [comment]
Would be really good to find a way to get write access to other folders too.
Meanwhile I think this warning is the best we can do. Thanks a lot.

**Comment by giedrioks26** [comment]
Or you can use external SD card as internal memory https://www.themobileindian.com/how-to/how-to-use-external-sd-card-as-internal-memory-on-your-android-smartphone-16453
It works. I am now using this. But the removed cards do not read other devices. This is a way to increase your space.
Maybe you should write this too?

**Comment by m-kuhn** [comment]
Very interesting, yes.
It would be great if this would be included in the docs too!

**Pull request merged**
