### PR TITLE
Proposal to update the docs theme

### PR DESCRIPTION
**Pull request by mbernasocchi**
Left current, right proposal.
@opengisch/devs please vote with :+1: and :-1: 

Screenshot from 2020-08-12 17-32-03
Screenshot from 2020-08-12 17-33-27

### CODE REVIEW

**Comment by mbernasocchi** [comment]
@nirvn also vote above please

**Comment by nirvn** [comment]
I'm +1 on the large logo removal, but I'm not sure how I feel about adding the dark marine blue color. It's not used in any parts of QField (vs. the dark gray that is being replaced which was in the QField palette already).

So +1 for logo removal, -1 for marine blue.

**Comment by signedav** [comment]
I like the marine blue header, but maybe there are alternatives better fitting into the color palette (maybe a dark grey).

**Comment by nirvn** [comment]
Don't get me wrong, I really like dark marine blue as a color, I just don't think it's useful to straight away from the color palette already used in QField.

**Comment by mbernasocchi** [comment]
@nirvn @opengisch/devs 
here the next proposal using the same theme as the bluemarine but reusing the QField green. For me it's ready to merge
Screenshot from 2020-08-15 02-11-35
Screenshot from 2020-08-15 02-11-41

**Pull request merged**
