### PR TITLE
cjk compliant font family

### PR DESCRIPTION
**Pull request by why-not-try-calmer**
This needs to be tested. I don't have access to the Chinese or Japanese translations.

Depends on #369.

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-2930 Fix Japanese and Chinese in Social Cards (Twitter etc)](https://app.clickup.com/t/2192114/QF-2930)

**Comment by why-not-try-calmer** [comment]
> @why-not-try-calmer I tested with `Noto Sans` font locally after pulling ja/zh from transifex. It does not work unfortunately. Looks like have to specify font like `Noto Sans JP` as social plugin example shows.
> 
> I think only a way is to use custmisation feature of social card (insiders' version) to insert font family for each language markdown file as I commented in the following issue.
> 
> [#355 (comment)](https://github.com/opengisch/QField-docs/issues/355#issuecomment-1633704527)

Okay, will do, thanks

**Comment by why-not-try-calmer** [comment]
@JinIgarashi By the way do you have a link to the page hosting the badly rendered social card?

**Comment by JinIgarashi** [comment]
@why-not-try-calmer I don't have it. But you can get link of social card from head tags in each html from developer tool of Chrome. Change any language code to ja/zh, you can get bad social code.

**Comment by why-not-try-calmer** [comment]
> @why-not-try-calmer I don't have it. But you can get link of social card from head tags in each html from developer tool of Chrome. Change any language code to ja/zh, you can get bad social code.

Devtools hum... But in what circumstances is the regular going to run into the issue? Sorry I am not super familiar with social cards but I am interested in the context in which this issue occurs.

**Comment by JinIgarashi** [comment]
@why-not-try-calmer For example, when you paste a link of website to social media like twitter or Facebook, LinkedIn, etc, normally social card image and site name and description will be shown if appropriate meta tags exists in html head.

this is important for readers to know what the link is without visiting website. Also, in terms of SEO, search engines like google can collect information from those metadata. 

If you want to advertise QField more through the internet, you should consider adding appropriate meta tags including social card.

**Comment by why-not-try-calmer** [comment]
Thanks, I'll come up with something.

**Comment by why-not-try-calmer** [comment]
This is expected to produce:
image

**Comment by JinIgarashi** [comment]
@why-not-try-calmer thanks, looks good.

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
