### PR TITLE
fix the green to QField green

### PR DESCRIPTION
**Pull request by mbernasocchi**
as per https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors

### CODE REVIEW

**Comment by m-kuhn** [comment]
What about the light and dark versions?

**Comment by marioba** [comment]
@mbernasocchi I tried it locally but I don't see any change. Did you try it?

**Comment by suricactus** [comment]
@mbernasocchi The QField logo has camoflouged better than needed in the top bar :)
image

**Comment by nirvn** [comment]
I think we can merge this alongside https://github.com/opengisch/QField-docs/pull/202

**Comment by m-kuhn** [comment]
Do we need to change a logo path too?

**Comment by nirvn** [comment]
@m-kuhn , I don't think so no.

One change that'd be nice is to tweak the configuration so the documentation's "night" mode keeps using the QField green as its main color.

**Review by marioba — APPROVED** [review]

**Pull request merged**
