### PR TITLE
better documentation about prefilling attributes

### PR DESCRIPTION
**Pull request by mbernasocchi**
@lucienicolier you can maybe add a very short video

### CODE REVIEW

**Review by lucienicolier — APPROVED** [review]

**Review by m-kuhn — APPROVED** [review]
Is there a difference between "remember" and "pre-fill"? Otherwise I would stick to one single terminology.

**Comment by lucienicolier** [comment]
@m-kuhn I think the checkbox gives you the chance to make it remember what you add in the attributes and then it pre-fill when you make a new feature. For my part I like it this way, what do you think @mbernasocchi ?

**Comment by m-kuhn** [comment]
For me it's ok to mention both in the text (concept and effect) but I would only use one in the title, to avoid that in trainings and blog posts some people talk about "pre-filling" and some talk about "remembering"

**Comment by lucienicolier** [comment]
@m-kuhn which one do you prefer?

**Comment by m-kuhn** [comment]
I think we used "remember" in the past so I'd stick to that

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
