### PR TITLE
Remove "SSL not supported" note from postgis

### LINKED ISSUE #51: Supported data formats
https://qfield.org/docs/project-management/dataformat.html

Is the note on the table about Postgis "Ssl support not yet implemented." still right?

### PR DESCRIPTION
**Pull request by lucienicolier**
This is no longer needed

Fix #51

### CODE REVIEW

**Comment by lucienicolier** [comment]
@m-kuhn is that right?

**Comment by m-kuhn** [comment]
Almost. Change the title to "Remove note: SSL not supported by postgis" and then change the "body text" to

"This no longer applies to newer versions

Fix ..."

**Comment by m-kuhn** [comment]
Pro tip number 2: you can click the edit button next to the title or on top of your comment to change the text.

**Comment by lucienicolier** [comment]
this time?

**Comment by m-kuhn** [comment]
I just adjusted it the way I think it's right :)

Please look at it and merge.

**Comment by lucienicolier** [comment]
where did you write the "#51"

**Comment by m-kuhn** [comment]
https://github.com/opengisch/QField-docs/pull/52#issue-407263974

**Pull request merged**
