### PR TITLE
How to activate the new button Interface for value map widgets

### PR DESCRIPTION
**Pull request by SeqLaz**
Adding description for the new interface of the value maps widgets

### CODE REVIEW

**Comment by nirvn** [comment]
@SeqLaz , thanks for this, I'll have a look later today or tomorrow -- one thing I can see already: could you use the refreshed bees farming project instead of the one you used to create the screenshots? That older one doesn't look half as good as the refreshed one.

**Comment by SeqLaz** [comment]
> @SeqLaz , thanks for this, I'll have a look later today or tomorrow -- one thing I can see already: could you use the refreshed bees farming project instead of the one you used to create the screenshots? That older one doesn't look half as good as the refreshed one.

Absolutely, let me take the screenshots

**Comment by nirvn** [comment]
@SeqLaz , also, can you take the screenshot with QField 3.3.3? Thanks.

**Comment by SeqLaz** [comment]
> @SeqLaz , also, can you take the screenshot with QField 3.3.3? Thanks.

The new screenshots were taken with QField 3.3.3.

**Pull request merged**
