### PR TITLE
New windows screens 2.0

### PR DESCRIPTION
**Pull request by ZsanettMed**
I changed the type of the screens (!! <-> !) and added the mobile phone frame to the screens which were taken on phones.

### CODE REVIEW

**Comment by marioba** [comment]
Looks very good

**Comment by suricactus** [comment]
@marioba why don't we merge this? Seems quite ready? I will suggest only to recreate the QField's "welcome screen" which cuts horizontal margins around the buttons (`getting_started_splashscreen.png`), but can easily be done in a follow up PR.

**Comment by suricactus** [comment]
Sorry for being that guy again, bu as I mentioned before, the screenshots are cutting some of the margins:
image

In 1) we see there is a "step" in the image and in 2) we see there is no margin to the edge of the phone.

**Comment by suricactus** [comment]
The margins issue goes for:

- documentation/assets/images/howto_featureform.png
- documentation/assets/images/getting_started_splashscreen.png
- documentation/assets/images/howto_identification.png
- documentation/assets/images/howto_selection.png
- documentation/assets/images/howto_sendto.png
- ... and pretty much all the screenshots on Android

**Comment by nirvn** [comment]
I'm going to be even _worse of a guy_ than @suricactus  here :wink:

For the storage documentation, I've used the new branding phone frame template, i.e. the hyper-simplified flattened gray frame:
image

I think that's a very good thing to do for a few reasons: 
a/ by going away from a specific type of phone frame (i.e. mostly samsung looking), we end up being more generic, which is good.
b/ it's a gazillion times easier to overlay as the frame borders are sharp, greatly reducing the risks of glitches like the ones @suricactus pointed out.

**Comment by suricactus** [comment]
Agreed with Mathieu, even though the flat frame seems to cut the corners too.

Anyway, I believe it is better to merge like this other than wait for another 2 weeks, so the users can enjoy screenshots without being outdated or seeing scary black buttons.

**Comment by nirvn** [comment]
Just so we're clear here: I'd rather have this merged now and re-visited later instead of holding onto a refresh for a few more weeks :)

**Comment by ZsanettMed** [comment]
Hey @suricactus you are "that guy" who helps to make it better. So no worries and thanks for your comments. Sometimes the screens and the frame has different size, so the fastes way without investigate too much time on it was to cut it. I am very happy about the new frame @nirvn. I will change them next week. Where can I find it?

**Comment by suricactus** [comment]
I am merging this now, but would be more than happy to have the fixed screenshots sooner than later.

**Review by suricactus — APPROVED** [review]

**Pull request merged**
