### PR TITLE
change Field type to Widget type

### PR DESCRIPTION
**Pull request by soester**
Would fix:
https://github.com/opengisch/QField/issues/1026

Just checked for the Range widget maybe there is more to be adapded? The documentation seems to rely on an older qgis version?

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks for the proposal.
I think the note "numerical input is enforced based on the type" still belongs to TextEdit. Range will always ever be numeric, regardless of the type. TextEdit will have the full potential back once https://github.com/opengisch/QField/pull/1031 is merged.

**Comment by mbernasocchi** [comment]
@m-kuhn can we merge this?

**Comment by m-kuhn** [comment]
I don't think it applies any more.
If you have a TextEdit with a numerical field, it only accepts numbers, correct @signedav ?
We could still adjust the title (Field Type -> Widget Type) if we want to.

**Comment by signedav** [comment]
I think you are right @m-kuhn since you fixed it here https://github.com/opengisch/QField/commit/d3ee9ebd5eae508b8466411a57f0397b1672709c
In case the issue persists (what I don't think), then this would be needed to fixed there and not in the doc...

**Pull request closed without merging**
