### PR TITLE
Adjust mkdocs-insiders version

### PR DESCRIPTION
**Pull request by why-not-try-calmer**
Can we do without insiders? I always forget why we need to declare it as a build dependency.

### CODE REVIEW

**Comment by suricactus** [comment]
It brings a bit extra things, don't remember exactly what. Last time I checked it was still used.

To test without merging we should rather add the insiders deps in the `lint-and-test` than commenting it in the `build` that only runs on master.

**Comment by why-not-try-calmer** [comment]
I think this begs for a removal or version bump of mkdocs-insiders.

**Comment by suricactus** [comment]
Found the culprit. It is the social plugin.

Tried with and a bit more, without success.:
```
  - social:
      # See https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/
      concurrency: 1
      debug: true
      log_level: warn
      cards_color:
        fill: "#72ad2e"
        text: "#FFFFFF"
```

I have reported the issue https://github.com/squidfunk/mkdocs-material/issues/6241 .

**Comment by suricactus** [comment]
See workaround solution here: https://github.com/opengisch/QField-docs/pull/391

**Pull request closed without merging**
